import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { motion } from 'framer-motion';
import { ArrowDown, ArrowRight, ArrowUpRight, Check, ChevronDown, Clock3, Flower2, Heart, Leaf, MapPin, Menu, Phone, Play, Sparkles, Stethoscope, Waves, X, MessageCircle, Camera, Star, BadgeCheck, ShieldCheck, Ruler, Video } from 'lucide-react';
import './styles.css';
import './sections.css';
import { TreatmentsPage, InsurancePage, HeightSessionPage } from './subpages.jsx';

const phonePrimary = '+918856031282';
const treatments = [
  { no: '01', icon: <Waves/>, title: 'Joint & spine care', desc: 'Find a gentler path back to moving with ease.', tags: ['Arthritis', 'Joint pain', 'Back pain', 'Sciatica', 'Cervical issues'], color: 'sage' },
  { no: '02', icon: <Flower2/>, title: 'Panchakarma detox', desc: 'Traditional therapies, thoughtfully tailored to you.', tags: ['Panchakarma', 'Takradhara', 'Rejuvenation', 'Restoration'], color: 'ochre' },
  { no: '03', icon: <Sparkles/>, title: 'Chronic & lifestyle', desc: 'Whole-person care for the concerns that linger.', tags: ['Women’s health', 'Fertility', 'Skin & hair', 'Diabetes', 'Weight care', 'Digestive health'], color: 'clay' },
];
const instagramUrl = 'https://www.instagram.com/aayu_tatva/';
const patientReviews=[
  {name:'Suhani Selote',initial:'S',type:'HEIGHT & GROWTH · GOOGLE REVIEW',text:'“My height was 151 cm. After two months, it had grown by 2.5 cm.”',translated:true},
  {name:'Sangita Shrawankar',initial:'S',type:'HEIGHT & GROWTH · GOOGLE REVIEW',text:'“After two months of treatment, my daughter’s height was 101 cm, up from 99 cm.”',translated:true},
  {name:'Kalyani Hatwar',initial:'K',type:'HEIGHT & GROWTH · GOOGLE REVIEW',text:'“My height was 153.5 cm; after one month, it was 154 cm.”',translated:true},
  {name:'Simran Besare',initial:'S',type:'PATIENT EXPERIENCE · GOOGLE REVIEW',text:'“The doctors explained the treatment clearly, and the staff were caring and supportive.”',translated:true},
  {name:'Shweta Pal',initial:'S',type:'PATIENT EXPERIENCE · GOOGLE REVIEW',text:'“Good result 👍👍”',translated:false},
  {name:'Lucky',initial:'L',type:'PATIENT EXPERIENCE · GOOGLE REVIEW',text:'“Good results 👍👍”',translated:false},
];
const clinicStories = [
  { reel: 'DTxZBDJjCjj', image: '/media/hospital-update.png', title: 'AayuTatva Reel', label: '21 JAN 2026' },
  { reel: 'DTP8HVhie2Z', image: '/media/sciatica-program.png', title: 'AayuTatva Reel', label: '08 JAN 2026' },
  { reel: 'DSfP7k_jOOt', image: '/media/growth-care.png', title: 'AayuTatva Reel', label: '20 DEC 2025' },
];
const reveal = { hidden: { opacity: 0, y: 26 }, show: { opacity: 1, y: 0, transition: { duration: .7, ease: [.22,1,.36,1] } } };

function App() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  const [form, setForm] = useState({ name: '', phone: '', department: '', date: '', note: '' });
  const submit = (e) => {
    e.preventDefault();
    const message = [
      'Hello AayuTatva, I would like to request an appointment.',
      '',
      `Name: ${form.name}`,
      `Phone: ${form.phone}`,
      `Area of care: ${form.department}`,
      `Preferred date: ${form.date}`,
      `Notes: ${form.note || 'Not provided'}`,
    ].join('\n');
    window.open(`https://wa.me/${phonePrimary.replace('+', '')}?text=${encodeURIComponent(message)}`, '_blank', 'noopener,noreferrer');
    setSubmitted(true);
  };
  const update = (e) => setForm({ ...form, [e.target.name]: e.target.value });
  return <>
    <header className="header"><a href="#home" className="brand" aria-label="AayuTatva home"><img className="brand-logo" src="/media/aayutatva-logo.png" alt="Dr. Yerpude’s AayuTatva Ayurved Hospital & Panchakarma Centre"/></a>
      <nav className={menuOpen ? 'nav open' : 'nav'}><a href="/treatments.html" onClick={()=>setMenuOpen(false)}>Treatments</a><a href="#doctors" onClick={()=>setMenuOpen(false)}>Our doctors</a><a href="/insurance.html" onClick={()=>setMenuOpen(false)}>Cashless care</a><a href="/height-session.html" onClick={()=>setMenuOpen(false)}>Height & growth</a><a href="#visit" className="nav-contact" onClick={()=>setMenuOpen(false)}>Contact</a><a href="#booking" className="nav-book" onClick={()=>setMenuOpen(false)}>Book consultation <ArrowUpRight size={15}/></a></nav>
      <div className="header-right"><a href={`tel:${phonePrimary}`} className="phone-head" aria-label="Call AayuTatva at +91 88560 31282"><Phone size={16}/><span>Call</span></a></div>
      <button className="menu-toggle" onClick={()=>setMenuOpen(!menuOpen)} aria-label="Toggle navigation">{menuOpen?<X/>:<Menu/>}</button>
    </header>
    <main id="home">
      <section className="hero">
        <div className="hero-copy"><motion.div initial="hidden" animate="show" variants={reveal} className="eyebrow"><span className="eyebrow-line"/> CARE, ROOTED IN NATURE</motion.div>
          <motion.h1 initial="hidden" animate="show" transition={{delay:.08}} variants={reveal}>Authentic Ayurvedic<br/>Healing Without<br/><em>Surgery.</em></motion.h1>
          <motion.p className="hero-sub" initial="hidden" animate="show" transition={{delay:.16}} variants={reveal}>Experience personalized Panchakarma and rooted natural clinical treatments directed by <strong>Dr. Manish Santosh Yerpude</strong> at AayuTatva Hospital.</motion.p>
          <motion.div className="hero-actions" initial="hidden" animate="show" transition={{delay:.22}} variants={reveal}><a className="btn-primary" href="#booking">Book consultation <ArrowUpRight size={16}/></a><a className="btn-text" href="#treatments">Explore treatments <ArrowRight size={17}/></a></motion.div>
          <motion.div className="hero-proof" initial="hidden" animate="show" transition={{delay:.3}} variants={reveal}><div className="proof-avatars"><span>M</span><span>A</span><span>+</span></div><p><b>Care that sees the whole you.</b><br/>Personal attention, at every step.</p></motion.div>
        </div>
        <div className="hero-visual"><div className="hero-image"><div className="image-wash"/><div className="image-note"><span>01 / 03</span><i/> THE WISDOM OF WELLNESS</div></div><div className="floating-seal"><span className="seal-icon"><Flower2 size={25}/></span><span>Rooted in<br/><b>Ayurveda</b></span></div><div className="hero-caption"><span>BHANDARA, MAHARASHTRA</span><span>21°10' N · 79°39' E</span></div></div>
        <a href="#approach" className="scroll-cue"><span>SCROLL TO EXPLORE</span><ArrowDown size={14}/></a>
        <div className="hero-vertical">A PLACE TO PAUSE. A PRACTICE THAT LISTENS.</div>
      </section>
      <section className="trust-strip" id="visit"><div className="trust-intro"><span className="mini-sun"><Sparkles size={17}/></span><span>GOOD HEALTH<br/><b>GROWS HERE</b></span></div><div className="trust-item"><span className="trust-icon"><Stethoscope size={18}/></span><div><small>YOUR DOCTOR</small><b>Dr. Manish Santosh Yerpude</b></div></div><div className="trust-item"><span className="trust-icon"><Clock3 size={18}/></span><div><small>OPEN EVERY DAY</small><b>10:00 AM – 7:00 PM</b></div></div><div className="trust-item address"><span className="trust-icon"><MapPin size={18}/></span><div><small>FIND US IN BHANDARA</small><b>1st Floor, Bawankar Bhavan, Khat Road<br/>Near Ganesh Marble, Shiv Nagari, Maharashtra 441904</b></div></div></section>
      <section className="credentials-strip"><div><span className="credentials-icon"><BadgeCheck size={19}/></span><span><small>QUALITY & TRUST</small><b>NABH-approved hospital</b></span></div><div><span className="credentials-icon"><ShieldCheck size={19}/></span><span><small>INSURANCE SUPPORT</small><b>Cashless requests for eligible IPD care</b></span></div><a href="/insurance.html">Insurance information <ArrowUpRight size={15}/></a></section>
      <section className="height-feature"><div className="height-feature-art"><div className="height-ruler"><span/><span/><span/><span/><span/><span/><span/></div><div className="height-plant"><i/><i/><i/><b/></div><span className="height-art-label">GROWTH, GUIDED WITH CARE</span></div><div className="height-feature-copy"><div className="section-kicker"><span>PERSONALIZED HEIGHT & GROWTH CONSULTATIONS</span><i/></div><h2>A thoughtful start<br/>to their <em>growth journey.</em></h2><p>Questions about a child’s height? Begin with a doctor-led consultation and an individual assessment. Growth varies from child to child, so we focus on understanding first—without promising a fixed height gain.</p><div className="height-feature-actions"><a className="btn-primary" href="/height-session.html">Join our free Zoom session <Video size={16}/></a><a className="under-link" href="/treatments.html#height-growth">Explore height consultations <ArrowUpRight size={15}/></a></div></div></section>
      <section className="intro section-pad" id="approach"><motion.div className="section-kicker" initial="hidden" whileInView="show" viewport={{once:true}} variants={reveal}><span>01 — OUR APPROACH</span><i/></motion.div><div className="intro-grid"><motion.h2 initial="hidden" whileInView="show" viewport={{once:true}} variants={reveal}>Healing begins<br/>when <em>we listen.</em></motion.h2><motion.div className="intro-text" initial="hidden" whileInView="show" viewport={{once:true}} variants={reveal}><p>Good care is never one-size-fits-all. At AayuTatva, ancient Ayurvedic wisdom meets considered, personal attention—so your path to feeling better can be your own.</p><a href="#booking" className="under-link">Get to know us <ArrowUpRight size={15}/></a></motion.div></div><div className="values-row"><div><span>01</span><b>Rooted in tradition</b><p>Time-honoured Ayurvedic practices.</p></div><div><span>02</span><b>Made personal</b><p>Care shaped around your needs.</p></div><div><span>03</span><b>Here in Bhandara</b><p>A welcoming space, close to home.</p></div></div></section>
      <section className="vision-mission"><div className="vision-mission-head"><div className="section-kicker"><span>OUR PURPOSE</span><i/></div><h2>Rooted in care.<br/><em>Guided by purpose.</em></h2></div><div className="vision-mission-grid"><article><span>OUR VISION</span><h3>Ayurveda, closer to home.</h3><p>Make thoughtful, patient-centred Ayurvedic and Panchakarma care accessible to families in Bhandara and nearby communities.</p></article><article><span>OUR MISSION</span><h3>Listen first. Care personally.</h3><p>Understand each person’s needs, offer individualized guidance, and support care with respect, clarity, and responsible clinical practice.</p></article></div></section>
      <section className="doctor-team" id="doctors"><div className="doctor-team-heading"><div><div className="section-kicker"><span>MEET YOUR CLINICAL TEAM</span><i/></div><h2>Experienced care,<br/><em>with a human touch.</em></h2></div><p>Meet the Ayurvedic clinicians behind your care at AayuTatva Hospital in Bhandara.</p></div><div className="doctor-profile-grid"><motion.article className="doctor-profile-card" initial={{opacity:0,y:24}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.15}} transition={{duration:.55}}><div className="doctor-portrait"><img src="/media/dr-manish-yerpude.jpg" alt="Dr. Manish Santosh Yerpude"/><span>AYURVEDA · PAIN MANAGEMENT</span></div><div className="doctor-profile-copy"><div className="section-kicker"><span>AYURVEDA CONSULTANT</span><i/></div><h3>Dr. Manish S.<br/><em>Yerpude</em></h3><p className="doctor-credentials">B.A.M.S. (MUHS) · MD (AM)</p><p className="doctor-reg">Registration No. I-117221-A</p><p className="doctor-bio">Consultations across pain management, bone and joint care, digestive health, skin concerns, and other Ayurvedic care needs.</p><div className="doctor-specialties"><span>PAIN MANAGEMENT</span><span>BONE & JOINT</span><span>DIGESTIVE HEALTH</span><span>SKIN DISORDERS</span></div><a href="/treatments.html#joint-spine" className="under-link">Explore areas of care <ArrowUpRight size={15}/></a></div></motion.article><motion.article className="doctor-profile-card" initial={{opacity:0,y:24}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.15}} transition={{duration:.55,delay:.12}}><div className="doctor-portrait"><img src="/media/dr-sakshi-sonkusare.jpg" alt="Dr. Sakshi G. Sonkusare"/><span>WOMEN’S HEALTH · SKIN · HAIR</span></div><div className="doctor-profile-copy"><div className="section-kicker"><span>CLINICAL COSMETOLOGIST & TRICHOLOGIST</span><i/></div><h3>Dr. Sakshi G.<br/><em>Sonkusare</em></h3><p className="doctor-credentials">B.A.M.S. (MUHS) · PGDCC</p><p className="doctor-reg">Registration No. I-117222-A</p><p className="doctor-bio">Consultations for women’s health, Garbha Sanskar, skin and hair concerns, trichology, digestive health, and related care.</p><div className="doctor-specialties"><span>WOMEN’S HEALTH</span><span>SKIN & HAIR</span><span>TRICHOLOGY</span><span>GARBHA SANSKAR</span></div><a href="/treatments.html#womens-health" className="under-link">Explore areas of care <ArrowUpRight size={15}/></a></div></motion.article></div></section>
      <section className="treatments section-pad" id="treatments"><div className="treatment-heading"><div><div className="section-kicker"><span>02 — HOW WE CAN HELP</span><i/></div><h2>Care for what<br/><em>matters to you.</em></h2></div><p>Every concern deserves a thoughtful conversation. Explore our areas of care, then let’s find the right next step together.</p></div><div className="treatment-grid">{treatments.map((t,i)=><motion.article className={`treatment-card ${t.color}`} key={t.no} initial="hidden" whileInView="show" viewport={{once:true,amount:.2}} variants={{hidden:{opacity:0,y:26},show:{opacity:1,y:0,transition:{duration:.55,delay:i*.12}}}}><div className="card-top"><span>{t.no} / 03</span><span className="card-icon">{t.icon}</span></div><h3>{t.title}</h3><p>{t.desc}</p><div className="tag-list">{t.tags.map(x=><span key={x}>{x}</span>)}</div><a href={`/treatments.html#${["joint-spine","panchakarma","lifestyle"][i]}`} className="card-link" aria-label={`Ask about ${t.title}`}>Explore care <ArrowUpRight size={16}/></a></motion.article>)}</div><p className="care-note"><Heart size={15}/> A consultation helps us understand your individual needs and recommend appropriate care.</p></section>
      <section className="stories section-pad" id="stories"><div className="stories-heading"><div><div className="section-kicker"><span>03 — AAYUTATVA ON INSTAGRAM</span><i/></div><h2>A little look at<br/><em>life at the clinic.</em></h2></div><a href={instagramUrl} target="_blank" rel="noreferrer" className="instagram-follow"><Camera size={17}/> Follow @aayu_tatva <ArrowUpRight size={15}/></a></div><div className="stories-grid">{clinicStories.map((story,i)=><motion.a href={`${instagramUrl}reel/${story.reel}/`} target="_blank" rel="noreferrer" className="story-card" key={story.reel} initial={{opacity:0,y:22}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.2}} transition={{duration:.55,delay:i*.1}}><div className="story-image"><img src={story.image} alt="AayuTatva clinic campaign"/><span className="story-play"><Play size={18} fill="currentColor"/></span><span className="story-label"><Camera size={12}/>{story.label}</span></div><div className="story-caption"><span>{story.title}<small>WATCH REEL · {story.label}</small></span><ArrowUpRight size={16}/></div></motion.a>)}</div><p className="story-note">Select a story to watch the Reel on our Instagram profile.</p></section>
      <section className="reviews section-pad" id="reviews"><div className="reviews-heading"><div><div className="section-kicker"><span>04 — PATIENT REVIEWS</span><i/></div><h2>Read patient feedback<br/><em>in context.</em></h2></div><div className="review-score"><strong>4.8</strong><div><span className="stars"><Star/><Star/><Star/><Star/><Star/></span><small>Google listing rating</small></div></div></div><div className="review-carousel-controls"><span>HEIGHT & GROWTH REVIEWS FIRST · SWIPE TO EXPLORE</span><div><button type="button" aria-label="Scroll reviews left" onClick={()=>document.getElementById('review-rail').scrollBy({left:-370,behavior:'smooth'})}>←</button><button type="button" aria-label="Scroll reviews right" onClick={()=>document.getElementById('review-rail').scrollBy({left:370,behavior:'smooth'})}>→</button></div></div><div className="reviews-grid review-rail" id="review-rail" aria-label="Patient review cards">{patientReviews.map((review)=><article className="review-card home-review-card" key={review.name}><div className="review-card-top"><span className="stars"><Star/><Star/><Star/><Star/><Star/></span><span className="review-source">{review.type}</span></div><p className="review-quote">{review.text}</p><div className="reviewer"><span>{review.initial}</span><div><b>{review.name}</b><small>{review.translated?'Translated excerpt · screenshot shared by clinic':'Google review · screenshot shared by clinic'}</small></div><BadgeCheck size={15}/></div></article>)}</div><p className="reviews-context-note">Patient-shared Google review excerpts. Height-related statements are individual, self-reported experiences—not verified treatment outcomes or a guarantee of results. Marathi excerpts are translated for readability.</p></section>
      <section className="quote-band"><div className="quote-leaf"><Leaf size={22}/></div><p>“The best way forward starts with<br/><em>a conversation, not a prescription.</em>”</p><span>— THE AAYUTATVA WAY</span></section>
      <section className="booking section-pad" id="booking"><div className="booking-copy"><div className="section-kicker"><span>05 — YOUR FIRST STEP</span><i/></div><h2>Let’s talk about<br/><em>your wellbeing.</em></h2><p>Tell us a little about what brings you here. Our team will be in touch to arrange a time that works for you.</p><div className="booking-call"><span className="call-icon"><Phone size={18}/></span><div><small>PREFER TO CALL?</small><a href={`tel:${phonePrimary}`}>+91 88560 31282 <ArrowUpRight size={14}/></a><span className="pulse-label"><i/> WE’RE HERE TO HELP</span></div></div></div>
        <motion.div className="form-card" initial="hidden" whileInView="show" viewport={{once:true}} variants={reveal}>{submitted?<div className="success-state"><span><Check size={26}/></span><h3>WhatsApp is ready, {form.name || 'there'}.</h3><p>We opened your appointment request in WhatsApp. Tap Send there to share it with the clinic.</p><button className="btn-primary" onClick={()=>setSubmitted(false)}>Request another appointment <ArrowRight size={16}/></button></div>:<><div className="form-heading"><span>APPOINTMENT REQUEST</span><span className="form-spark"><Sparkles size={17}/></span><p>A few details, and we’ll take it from here.</p></div><form onSubmit={submit}><label>Your name<input name="name" value={form.name} onChange={update} placeholder="e.g. Priya Sharma" required autoComplete="name"/></label><div className="form-row"><label>Phone number<input type="tel" name="phone" value={form.phone} onChange={update} placeholder="+91 00000 00000" required autoComplete="tel" pattern="[+0-9 ()-]{10,}"/></label><label>Area of care<span className="select-wrap"><select name="department" value={form.department} onChange={update} required><option value="" disabled>Select an area</option><option>Height & growth</option><option>Joint & spine care</option><option>Panchakarma & Takradhara</option><option>Digestive health</option><option>Skin & scalp care</option><option>Women’s health & PCOD</option><option>Fertility & infertility</option><option>Diabetes management</option><option>Weight management</option><option>Hair & trichology</option><option>Garbha Sanskar</option><option>Not sure yet</option></select><ChevronDown size={16}/></span></label></div><label>Preferred date<input type="date" name="date" value={form.date} onChange={update} min={new Date().toISOString().split('T')[0]} required/></label><label>Anything you’d like us to know? <span className="optional">OPTIONAL</span><textarea name="note" value={form.note} onChange={update} placeholder="Share a little about what brings you in…" rows="3"/></label><button type="submit" className="btn-primary submit-btn">Request an appointment <ArrowUpRight size={16}/></button><p className="privacy-note">Submitting opens WhatsApp. Review the message and tap Send to contact the clinic.</p></form></>}</motion.div>
      </section>
      <section className="visit-band"><div className="visit-text"><span>WE’D LOVE TO WELCOME YOU</span><h2>Find your way<br/><em>to feeling better.</em></h2><a href="https://maps.google.com/?q=1st+Floor+Bawankar+Bhavan+Khat+Road+Bhandara+Maharashtra+441904" target="_blank" rel="noreferrer" className="map-link"><MapPin size={17}/> Get directions <ArrowUpRight size={15}/></a></div><div className="visit-details"><div><small>COME SEE US</small><p>1st Floor, Bawankar Bhavan<br/>Khat Road, near Ganesh Marble<br/>Shiv Nagari, Bhandara<br/>Maharashtra 441904</p></div><div><small>OPEN DAILY</small><p>Monday to Sunday<br/>10:00 AM – 7:00 PM</p></div></div><div className="visit-decoration"><Flower2 size={145}/></div></section>
    </main>
    <footer className="footer"><div className="footer-main"><a href="#home" className="brand footer-brand"><img className="brand-logo" src="/media/aayutatva-logo.png" alt="Dr. Yerpude’s AayuTatva Ayurved Hospital & Panchakarma Centre"/></a><p>Rooted in nature.<br/>Guided by care.</p><div className="footer-phones"><a href="tel:+918856031282"><Phone size={16}/> +91 88560 31282</a><a href="tel:+917758816074"><Phone size={16}/> +91 77588 16074</a></div><a className="footer-book" href="#booking">Book your consultation <ArrowUpRight size={16}/></a></div><div className="footer-bottom"><span>© 2026 AayuTatva Ayurvedic Hospital & Panchakarma Centre</span><span>DR. MANISH SANTOSH YERPUDE · BHANDARA</span><a href="#home">BACK TO TOP ↑</a></div></footer>
    <a href="https://wa.me/918856031282" target="_blank" rel="noreferrer" className="whatsapp" aria-label="Chat with AayuTatva on WhatsApp"><MessageCircle size={22}/><span>WhatsApp us</span></a>
  </>;
}

const path = window.location.pathname;
const Page = path === '/treatments.html' ? TreatmentsPage : path === '/insurance.html' ? InsurancePage : path === '/height-session.html' ? HeightSessionPage : App;
createRoot(document.getElementById('root')).render(<Page/>);
